services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: obligatorio-backend
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3001:3001" 
    environment:
      - NODE_ENV=development
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: obligatorio-frontend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0
    stdin_open: true
    tty: true
