services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: obligatorio-backend
    volumes:
      - ./backend:/usr/src/app
      - ./backend/data:/usr/src/app/data 
      - /usr/src/app/node_modules
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=obligatorio_db
      - DB_USER=obligatorio_user
      - DB_PASSWORD=obligatorio_pass
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: obligatorio-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: obligatorio_db
      MYSQL_USER: obligatorio_user
      MYSQL_PASSWORD: obligatorio_pass
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: obligatorio-frontend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0
    stdin_open: true
    tty: true

volumes:
  mysql_data:
