services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: obligatorio-backend
    volumes:
      - ./backend:/usr/src/app
      - ./backend/data:/usr/src/app/data 
      - /usr/src/app/node_modules
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - DB_HOST=mysql.reto-ucu.net
      - DB_PORT=50006
      - DB_NAME=AM_Grupo2
      - DB_USER=am_g2_admin
      - DB_PASSWORD=8AS3S_Grup0_2

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: obligatorio-frontend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0
    stdin_open: true
    tty: true
